### ISSUE TITLE
Sessions not being saved

### ISSUE THREAD

**Issue by hmajid2301** [ofirgall/tmux-browser#4]
Hi :wave:,

The plugin opens a new browser window when I attach to a tmux session however any changes I make to the browser don't get saved. It also doesn't close the browser on detach.
I also had to manually create the folder at `$HOME/.tmux/browser-sessions` the plugin didnt seem to do that.

So I feel like something is not being configured correctly.

My tmux config: https://gitlab.com/hmajid2301/dotfiles/-/blob/main/tmux/.tmux.conf

```
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g base-index 1
set -s escape-time 0
set -g mouse on

set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind r source-file ~/.tmux.conf

# Escape turns on copy mode
bind Escape copy-mode
set-window-option -g mode-keys vi

# v in copy mode starts making selection
bind-key -T copy-mode v send -X begin-selection
bind-key -T copy-mode y send -X copy-selection

# make Prefix p paste the buffer.
unbind p
bind p paste-buffer

# Mac Os Command+K (Clear scrollback buffer)
bind -n C-k clear-history

# Set a larger scroll back
set-option -g history-limit 100000
set-option -g default-shell /usr/local/bin/fish

# A quiter setup
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session
set -g @t-fzf-prompt '  '

set -g @browser_close_on_deattach '1'
set -g @browser_launch_on_attach '1'

## Restore Vim sessions
set -g @resurrect-strategy-vim 'session'
## Restore Neovim sessions
set -g @resurrect-strategy-nvim 'session'
## Restore Panes
set -g @resurrect-capture-pane-contents 'on'
## Restore last saved environment (automatically)
set -g @continuum-restore 'on'
set -g @continuum-boot 'on'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'aserowy/tmux.nvim'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'ofirgall/tmux-browser'
run-shell $HOME/dotfiles/tmux/theme.sh

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'


````

Any ideas ? what could be causing it ?

**Comment by ofirgall** [comment]
Hey, does `~/.tmux/plugins/tmux-browser` exists? if not you should tell tpm to install the plugin `ctrl+b` `shift+i`

**Comment by hmajid2301** [comment]
I have installed the plugin  and that folder does exist. The plugin does manage to open a browser, and the default shortcut also works to open a browser.

**Comment by ofirgall** [comment]
Great! does [brotab](https://github.com/balta2ar/brotab) works for you? `bt list` should list all your active tabs

**Comment by hmajid2301** [comment]
interesting the browser is opened but `brotab list` returns empty. 

![image](https://user-images.githubusercontent.com/998807/234357512-00d8840d-e553-4cfb-b254-8d4f3280adea.png)
![image](https://user-images.githubusercontent.com/998807/234357559-f34f498d-16f9-448a-91ac-5ab4f39a1457.png)

(ignore the colours :laughing: XD, Im playing around)

Ahh I also noticed this happens; 

![image](https://user-images.githubusercontent.com/998807/234357737-5530511b-b207-445c-93a7-93133f4d2059.png)

then it throws an error after the browser window opens

![image](https://user-images.githubusercontent.com/998807/234357889-480beade-bb5e-4bfe-8726-45083b75e1da.png)

**Comment by ofirgall** [comment]
Hey, it looks like wmctrl fails to change focus to the new browser, but it doesn't really matter, you need to fix brotab in order the plugin to work, please open an issue at the brotab repo

**Comment by hmajid2301** [comment]
The issue was related to wayland not working with `wmctrl` removing that fixed the issue. It seems my DE auto focuses on the new window anyways.
